### ISSUE TITLE
code/ is missing BattleShipGame.h

### ISSUE THREAD

**Issue by JayBazuzi** [approvals/ApprovalTests.cpp.StarterProject#1]
I'm trying to build this and failing because ApprovalTests.Cpp.StarterProject/code/CMakeLists.txt has:

```
set(SOURCE_FILES
        BattleShipGame.h)
```

Maybe forgot a `git add`?

**Comment by isidore** [comment]
No, forgot to clean up properly :-| 
Fixed in  96ecf58

**Comment by isidore** [comment]
just fyi, it's not windows ready (still path dependent, and probably other things... )
