### ISSUE TITLE
Reinstate CMake changes from PR #3

### ISSUE THREAD

**Issue by claremacrae** [approvals/ApprovalTests.cpp.StarterProject#5]
We merged the changes in #3 and it broke the Travis builds.
https://travis-ci.org/approvals/ApprovalTests.cpp.StarterProject/builds/552962894

We'd like the changes, but first need to work out how to fix the Travis build...

**Comment by jmossberg** [comment]
Hi again,

I looked at your Travis CI build. There are compiler errors with regards to raw string literals in ApprovalTests.v.3.4.1.hpp among other things. I cannot explain why you don't get that prior to refactoring the CMakeLists.txt.

What worked in my fork of your repository was to change the Ubuntu distribution from trusty to bionic. The trusty distribution comes with g++ version 4.8.4. The bionic distribution comes with a more recent version of the g++ compiler (7.4.0) that does not complain about ApprovalTests.v.3.4.1.hpp.

Before changing to bionic: https://travis-ci.org/jmossberg/ApprovalTests.cpp.StarterProject/builds/554934603
After changing to bionic: https://travis-ci.org/jmossberg/ApprovalTests.cpp.StarterProject/builds/554935199

Another disadvantage with g++ version 4.8.4 is lack of support  for C++17 as far as I understand.

//Jacob

**Comment by jmossberg** [comment]
Hi again :),

I have setup a small git repository to experiment with the raw string literal from ApprovalTests.v.3.4.1.hpp  that caused the compiler to emit an error:
https://github.com/jmossberg/cpp-raw-string-literals/blob/master/cpp-raw-string-literals.cpp

I also configured a Travis CI build for the new repository. I get the same compiler error when I use the trusty distribution. After changing to bionic distribution it works.

Failed build with trusty (g++ 4.8.4): https://travis-ci.org/jmossberg/cpp-raw-string-literals/builds/554942215
Successful build with bionic (g++ 7.4.0): https://travis-ci.org/jmossberg/cpp-raw-string-literals/builds/554942570

//Jacob

**Comment by claremacrae** [comment]
Hi Jacob, thanks very much for all your efforts on this.

For building the ApprovalTests.cpp, the C++ requirement is C++11. 

(For running its tests, it's C++17 - but as this is the starter project, by design we wish to know that the starter project builds with C++11)

**Comment by claremacrae** [comment]
I've been doing some comparing of ApprovalTests.cpp and ApprovalTests.cpp.StarterProject

The .travis.yml files are different:

* ApprovalTests.cpp uses:
  * `cmake -DCMAKE_CXX_COMPILER=g++-6 ..`
* ApprovalTests.cpp.StarterProject uses:
  * `cmake -DCMAKE_CXX_COMPILER=$COMPILER ..`

Also, in the cmake files:

* ApprovalTests.cpp/ApprovalTests uses:
  * `set(CMAKE_CXX_STANDARD 11)`
* ApprovalTests.cpp.StarterProject/lib (with the PR 3 code) uses:
  * `set(TARGET StarterProject.lib PROPERTY CXX_STANDARD 17)`

**Comment by claremacrae** [comment]
I'm starting to think that a PR that modernises CMake code ideally shouldn't also change the behaviour of the builds...

By all means, we can later build against a wider variety of compilers, versions and OSes in future. However, coupling that with changes that are intended only to modernise CMake seems like too big a change for a single step.

**Comment by claremacrae** [comment]
I'm starting to think that this argument is crucial, and missing from the travis file in the StarterProject build:

`-DCMAKE_CXX_COMPILER=g++-6`

**Comment by jmossberg** [comment]
I agree that it is not good having to update the Travis build in the same step as refactoring the CMake files. Probably better to do those things separately as you say.

Regarding the "-DCMAKE_CXX_COMPILER=g++-6" argument. My understanding is that this argument shall only be used if we want to force a specific compiler to be used. If we remove this argument cmake will pick whatever is the default compiler for a particular distribution.

**Comment by jmossberg** [comment]
Hi Clare!

I had another go at this. :) I have forked your repository and added one commit where I refactor the cmake files. The goal is to follow how I understand so called "Modern CMake" guidelines:
- Set dependencies and properties on targets directly using e.g. target_link_libraries
- Avoid setting global settings through e.g. include_directories 

I have setup travis to run on my forked repository. My travis build is passing.

**Forked repository:** https://github.com/jmossberg/ApprovalTests.cpp.StarterProject
**Commit:** https://github.com/jmossberg/ApprovalTests.cpp.StarterProject/commit/ed2bac3e2600bb70b737fa19785c9289ee779911
**Successful travis build:** https://travis-ci.org/jmossberg/ApprovalTests.cpp.StarterProject/builds/612480001

**Comment by claremacrae** [comment]
Hi Jacob

It was great to meet you at Meeting C++!

I'm just catching up on email now, still at the hotel...

I've had a look at the diff and it looks really good to me... I like the use of different variables for the target names...

I'd really appreciate a PR for this if you have time...

Thanks again for helping us improve our CMake scripts...

Clare

**Comment by claremacrae** [comment]
The PR for this was #8, now merged... thanks Jacob!

**Comment by jmossberg** [comment]
Hi Clare,
yes it was very nice to meet you too at Meeting C++! :)
//Jacob
